project:
  type: website
  output-dir: quarto

website:
  title: "SPARC Building Scan"
  navbar:
    left:
      - href: quarto_book/intro_to_building_scan.md
        text: Building Scan
      - href: quarto_book/sparc_introduction.md
        text: What is SPARC?
      - href: notebooks/SPARC_building_scan_example.ipynb
        text: Analysis Notebook

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  warning: false
  message: false
